config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    member do
      get 'followings'
      get 'followers'
      get 'favorites'
    end
  end
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end
  
  
  
  
  
  
  
  
  

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorite,class_name: "Micropost"
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :region, length: {maximum: 60 }
  validates :profile,length: {maximum: 160 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    
  has_secure_password
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower  

  has_many :favorites
  
  has_many :favorite_microposts, through: :favorites, source: :favorite
  
  # 他のユーザーをフォローする
  def follow(other_user)
    # Relationship.find_or_create_by(followed_id: other_user.id, following_id: id)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    # Relationship.find_by(followed_id: other_user.id, following_id: id).present?
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  def favorite(other_micropost)
    favorites.find_or_create_by(favorite_id: other_micropost.id)
  end

  def unfavorite(other_micropost)
    favorite = favorites.find_by(favorite_id: other_micropost.id)
    favorite.destroy if favorite
  end
  
  def favorite?(other_micropost)
    favorite_microposts.include?(other_micropost)
  end
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_i18n_locale_from_params
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t('flash.application_login')
      redirect_to login_url
    end
  end
  
  protected
  def set_i18n_locale_from_params
    I18n.locale = extract_locale_from_tld || I18n.default_locale
  end
  
  def extract_locale_from_tld
    parsed_locale = request.subdomains.first
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in_user

  def create
    @micropost = Micropost.find(params[:favorite_id])
    current_user.favorite(@micropost)
  end

  def destroy
    @micropost = current_user.favorite_microposts.find(params[:favorite_id])
    current_user.unfavorite(@micropost)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = t('flash.micropost_create')
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = t('flash.micropost_destroy')
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content, :image, :image_cache)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = t('flash.session_create_login', user_name: @user.name)#"logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = t('flash.session_create_invalid')
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :confirm_user, only:[:edit, :update, :favorite]
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('flash.user_create')
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = t('flash.user_update')
      redirect_to @user
    else
      render 'edit'
    end
  end 
  
  def followings
    @user = User.find(params[:id])
    @followingusers = @user.following_users.order(created_at: :desc)
  end
  
  def followers
    @user = User.find(params[:id])
    @followerusers = @user.follower_users.order(created_at: :desc)
  end
  
  
  def favorites
    @user = current_user
    @favorite_microposts = @user.favorite_microposts.order(created_at: :desc)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :region, :profile, :password,
                                 :password_confirmation, :avatar, :avatar_cache, :remove_avatar)
  end
  
  def confirm_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def image_for(micropost)
    link_to image_tag(micropost.image.url, size:"500x500", alt: micropost.content, class: "img"),micropost.image.url if micropost.image?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def avatar_for(user, options = { size: "80x80" })
    image_tag(user.avatar.url, alt: user.name, size: options[:size], class: "gravatar")
  end
end

app/views/favorites/create.js.erb
$("#favorite_form_<%= @micropost.id %>").html("<%= escape_javascript(render 'microposts/unfavorite', favorite: @micropost ) %>");

app/views/favorites/destroy.js.erb
$("#favorite_form_<%= @micropost.id %>").html("<%= escape_javascript(render 'microposts/favorite', favorite: @micropost ) %>");

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('common.home'), root_path %></li>
        <li><%= link_to t('common.help'), '#' %></li>
        <% if logged_in? %>
        
          <!-- <li><%#= link_to t('common.users'), '#' %></li> -->
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('common.users') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('common.followings'), followers_user_path(current_user) %></li>
              <li><%= link_to t('common.followers'), followings_user_path(current_user) %></li>
            </ul>
          </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('common.account') %>  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('common.profile'), current_user %></li>
              <li><%= link_to t('common.favorites'), favorites_user_path(current_user) %></li>
              <li><%= link_to t('common.settings'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('common.logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('common.login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :favorite_id, favorite.id %></div>
  <%= f.submit t('common.favorite'), class: "btn btn-primary" %>
<% end %>

app/views/microposts/_favorite_form.html.erb
<div id="favorite_form_<%= favorite.id %>" >
  <% if current_user.favorite?(favorite) %>
    <%= render 'microposts/unfavorite', favorite: favorite %>
  <% else %>
    <%= render 'microposts/favorite', favorite: favorite %>
  <% end %>
</div>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <% if micropost.user.avatar? %>
    <%= link_to avatar_for(micropost.user, size:"50x50"), micropost.user %>
  <% else %>
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <% end %>
  
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_for micropost %>
  </span>
  <span class="timestamp">
    <%= t('common.posted') %> <%= time_ago_in_words(micropost.created_at) %> <%= t('common.ago') %>
    <% if current_user == micropost.user %>
      <%= link_to t('common.delete'), micropost, method: :delete,
                                       data: { confirm: t('common.yousure') } %>
    <% else %>
      <%= render 'microposts/favorite_form',  favorite: micropost  if logged_in? %>
    <% end %>
  </span>
</li>

app/views/microposts/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(favorite_id: favorite.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <div><%= hidden_field_tag :favorite_id, favorite.id %></div>
  <%= f.submit t('common.unfavorite'), class: "btn" %>
<% end %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('common.form_contains_error',error: pluralize(object.errors.count,t('common.error'), t('common.errors')  )) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t('common.micropost_placeholder') %>
    <%= image_for @micropost %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <%= f.submit t('common.post'), class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<% if current_user.avatar? %>
  <%= link_to avatar_for(current_user, size:"50x50"), current_user %>
<% else %>
  <%= link_to gravatar_for(current_user, size: 50), current_user %>
<% end %>

<h1><%= current_user.name %></h1>
<span><%= link_to t('common.view_my_profile'), current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t('common.Micropost_Feed')%></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t('common.Welcom_message')%></h1>

    <%= link_to t('common.Welcom_message'), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t('common.follow'), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_follow_profile.html.erb
<li>
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
      
      <% if follow_profile.avatar? %>
        <%= link_to avatar_for(follow_profile, size: "50x50") , follow_profile %>
      <% else %>
        <%= link_to gravatar_for(follow_profile, size: 50), follow_profile %>
      <% end %>
      
      <span class="user"><%= link_to follow_profile.name,follow_profile %></span>
      <p class="profile"><%= follow_profile.profile %></p>
    </div>
</li>

app/views/users/_profile.html.erb
<section class="user_info">
  <h1>
    <% if @user.avatar? %>
      <%= avatar_for @user %>
    <% else %>
      <%= gravatar_for @user %>
    <% end %>
    
    <%= @user.name %>
  </h1>
</section>
<section>
  <h2>
    <span class="label label-info"> <%= t('common.email') %> </span><br>
    <%= @user.email %>
  </h2>
  <h2>
    <span class="label label-info"> <%= t('common.region') %></span><br>
    <%= @user.region %>
  </h2>
  <h2>
    <span class="label label-info"> <%= t('common.profile') %></span><br>
    <%= @user.profile %>
  </h2>
</section>
<section>
  <h1>
    <%= link_to t('common.Microposts'), user_path(@user) %>
    <%= link_to t('common.followings'), followings_user_path(@user) %>
    <%= link_to t('common.followers'), followers_user_path(@user) %>
  </h1>
</section>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit t('common.unfollow'), class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('common.editprofile') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :avatar %><br>
      <% if @user.avatar? %>
        <%= image_tag(@user.avatar.url, alt: @user.name, class: "gravatar") %>
        <span class="form-inline">
          <br><%= f.label :remove_avatar, t('common.removeavatarimage') %>
          <%= f.check_box :remove_avatar, class: 'form-control'%><br>
        </span>
      <% else %>
        <%= gravatar_for @user %>
      <% end %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :region %>
      <%= f.text_field :region, class: 'form-control' %>

      <%= f.label :profile %>
      <%= f.text_area :profile, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, t('common.confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t('common.changemyprofile'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'profile' %>
  </aside>
  <div class="col-md-8">
      <h3><%= t('common.favorites') %> (<%= @favorite_microposts.count %>)</h3>
      <ol class="microposts">
        <%= render partial: 'microposts/micropost', collection: @favorite_microposts %>
      </ol>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'profile' %>
  </aside>
  <div class="col-md-8">
      <h3><%= t('common.followers') %>(<%= @followerusers.count %>)</h3>
      <ol class="microposts">
        <%= render partial: 'follow_profile', collection: @followerusers %>
      </ol>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'profile' %>
  </aside>
  <div class="col-md-8">
      <h3><%= t('common.followings') %> (<%= @followingusers.count %>)</h3>
      <ol class="microposts">
        <%= render partial: 'follow_profile', collection: @followingusers %>
      </ol>
  </div>
</div>

app/views/users/new.html.erb
<h1><%= t('common.signup') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, t('common.confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t('common.createmyaccount'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'profile' %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= t('common.Microposts') %> (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>